### ISSUE TITLE
`onDidReloadKeymap` and other methods should return disposable / unlistener

### ISSUE THREAD

**Issue by bengotow** [atom/atom-keymap#101]
It would be really helpful to follow the pattern of returning disposables or "unlisten" functions from the atom-keymap methods:

```coffee
# add listener
@unlisten = atom.keymaps.onDidReloadKeymap =>
    ...

# remove listener
@unlisten() 
```

I don't know that there's a strong case against doing this, and we need to create an intermediate that /can/ be unsubscribed to in order to link `atom.keymaps` to a React component (a preferences tab). Would be happy to submit a PR if it sounds good!

**Comment by nathansobo** [comment]
Hi @bengotow. This method returns a `Disposable`. You can call `.dispose()` on it to unsubscribe. Please reopen if I'm misunderstanding something.
