### ISSUE TITLE
Right ALT - diacritical letters problem "ó"

### ISSUE THREAD

**Issue by bazilazi** [atom/atom-keymap#103]
It's hardly to use Atom with polish keyboard. The letters like "ó" (Right ALT + o) don't work.

**Comment by 50Wliu** [comment]
Duplicate of atom/atom-keymap#35 and atom/atom-keymap#37, please subscribe there for updates.  Also try installing the [keyboard-localization](https://atom.io/package/keyboard-localization) package.
