### ISSUE TITLE
 character inserted on "ctrl-alt-shift-down/up"

### ISSUE THREAD

**Issue by yay** [atom/atom-keymap#106]
Hello,

I'm trying to set up keyboard shortcuts for moving between diffs in Atom like in WebStorm:
```
'atom-text-editor':
  'ctrl-alt-shift-down': 'git-diff:move-to-next-diff'

'atom-text-editor':
  'ctrl-alt-shift-up': 'git-diff:move-to-previous-diff'
```

What I get is the  character every time I use them.

Atom 1.2.4
Mac OS 10.11.1

**Comment by izuzak** [comment]
Which keyboard layout are you using? Can you post a screenshot of what the keybinding resolver shows when you hit that keystroke `ctrl-alt-shift-down/up`?

I just tried pasting that snippet to my keymap.cson file and the keybindings work just fine for me (the cursor moves to the previous/next diff) and I don't see the  charcter. However, after I remove those keybindings (they no longer exist in Atom), I do see that character  when I press `ctrl-alt-shift-down/up`. So, I'm guessing something is not being called correctly in your case.

**Comment by yay** [comment]
I don't know where to look for that.
I have "U.S." input source set in the Preferences.

**Comment by izuzak** [comment]
https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings for the keybinding resolver

**Comment by yay** [comment]
It just says
<img width="245" alt="screen shot 2015-11-27 at 3 43 16 pm" src="https://cloud.githubusercontent.com/assets/1799756/11443454/a68641c0-951d-11e5-8856-7c300b2af552.png">
BTW, I don't see the custom keybinding I put into the keymap.cson in the Preferences -> Keybindings grid:
<img width="623" alt="screen shot 2015-11-27 at 3 41 17 pm" src="https://cloud.githubusercontent.com/assets/1799756/11443510/fb4a5dcc-951d-11e5-927f-b20c190bf9de.png">
My other custom keybindings like cmd-b for toggle bookmark show up there.

**Comment by izuzak** [comment]
Strange, it shows up just fine for me. Mind sharing the full contents of your keymap.cson file?

**Comment by yay** [comment]
Sure, the uncommented part:
```

'atom-text-editor:not([mini])':
  'cmd-e': 'editor:delete-line'

'.platform-darwin atom-text-editor':
  'cmd-b': 'bookmarks:toggle-bookmark'

'atom-text-editor':
  'cmd-shift-b': 'bookmarks:view-all'

'atom-text-editor':
  'ctrl-alt-shift-down': 'git-diff:move-to-next-diff'

'atom-text-editor':
  'ctrl-alt-shift-up': 'git-diff:move-to-previous-diff'

'atom-text-editor':
  'ctrl-alt-shift-d': 'git-diff:toggle-diff-list'

```

**Comment by izuzak** [comment]
Thanks. You're overwriting the `atom-text-editor` key by listing it multiple times. You need to group values  so that you list `atom-text-editor` only once. See https://atom.io/docs/latest/using-atom-basic-customization#configuring-with-cson

**Comment by yay** [comment]
Oh, glad it's not an issue with Atom. I guess, I followed `You can override these keybindings by copying <clipboard icon> and pasting them into your keymap files` quite literally :) Thank you for your help!
