### ISSUE TITLE
Key Binding to Move File to Different Pane

### ISSUE THREAD

**Issue by AnthonyBobsin** [atom/atom-keymap#107]
Hello,

There are already keybindings to move across panes, and create new panes, but one thing that is currently missing is the ability to move a file to an adjacent pane. For example, if I have two vertically split panes, in order to move one file from the left pane to the right pane, I would have to use my mouse to drag the tab across. Forgive me if there is already a key binding for this, I've had no luck searching for it.

**Comment by mnquintana** [comment]
You can always add your own keybinding for this – please take a look at https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings.

In this case though, there is no command to "move" a file to another pane, but there is a command to open a new pane for a file (search the Command Palette for the `Pane: Split` commands). For the former, feel free to subscribe to https://github.com/atom/atom/issues/2670.
