### ISSUE TITLE
How to add keybindings for commands not in list

### ISSUE THREAD

**Issue by kumarharsh** [atom/atom-keymap#108]
I want to add a keybinding for `Editor: Split Selection into Lines` as `Ctrl+Shift+L` like I have in Sublime. This command does not have any keybinding assigned, so I can't search it in **Settings/Keybindings**. How do I add the keybinding?

**Comment by lee-dohm** [comment]
See my post on Discuss for [how to convert Command Palette names to command names.](https://discuss.atom.io/t/how-to-list-command-identifiers-not-descriptions-for-keybind/13391/2?u=leedohm) If you want the keybinding to be active within the editor (and for this command, that's what I assume), the selector would be `atom-text-editor`.

**Comment by kumarharsh** [comment]
ah, that was pretty straight-forward. thanks!

**Comment by lee-dohm** [comment]
You're welcome! Let us know if you have any other questions :grinning:
