### ISSUE TITLE
Keymap completely inert

### ISSUE THREAD

**Issue by mattecapu** [atom/atom-keymap#111]
What's the problem with [this](https://gist.github.com/mattecapu/f95ba2b4a1198e02a5d3) keymap.cson file?
The keymap seems to be disabled because the keybinding resolver doesn't even show the definitions. No error is raised by Atom.
When I remove everything but the `body` selector makes it work, but:
```cson
{
  'body': {
    'ctrl-shift-S': 'window:save-all',
    'alt-1': '',
    'alt-2': '',
    'alt-3': '',
    'alt-4': '',
    'alt-5': '',
    'alt-6': '',
    'alt-7': '',
    'alt-8': '',
    'alt-9': ''
  },
  'atom-text-editor': {
    'f2': 'refactor:rename'
  }
}
```
Does not work, while switching the order of the declarations does. No syntax error is raised on any of this configurations.
I'm running Atom 1.4.1 on Windows 10.

**Comment by lee-dohm** [comment]
It is either choking on the JSON-style syntax (though I'm not certain about that) or the empty-strings as the command names. When I took out the extra JSON-style formatting and removed the lines with the empty-string command names ... the two remaining keybindings both worked fine.

If you want to unset a keybinding, you should use the `unset!` directive as described in the [Keybindings In-Depth section of the Atom Flight Manual](https://atom.io/docs/latest/behind-atom-keymaps-in-depth#removing-bindings).

Let us know if that doesn't fix the issues you're running into!
