### ISSUE TITLE
OS X's Dvorak-Qwerty mode does not work.

### ISSUE THREAD

**Issue by donmccurdy** [atom/atom-keymap#12]
See [atom+dvorak discussion in the forums](http://discuss.atom.io/t/dvorak-with-qwerty-shortcuts-layout/2023).

For developers who type with the Dvorak keyboard layout, universal shortcuts like `Cmd+C` require two hands, which wastes time. As a result, most OS X users who type with Dvorak use the operating system's built-in "Dvorak Qwerty" mode, which automatically reverts to Qwerty when keys like `Cmd` or `Ctrl` are pressed, so that we can use the same hotkeys as everyone else.

Unfortunately, this doesn't seem to work in Atom – with `Cmd` pressed, the keys still map to their Dvorak equivalents. This is a common problem in Java-based IDEs (Eclipse, Netbeans, PHPStorm, ... ) and is one reason I've stuck with Sublime Text – which does not have this issue – for so long. Interestingly, I have never found an application in the App Store with the problem, so I would assume it has something to do with how key events are read from the operating system (Atom should not, in theory, need to know anything about my chosen keyboard layout).

You can try this mode on any Mac:

![screenshot](https://dl.dropboxusercontent.com/u/42869844/ftb/2014/Screen_Shot_2014-04-14_at_12_08_10_PM.png)

The only workaround I know of would be for me to manually override every hotkey of every plugin, which isn't really up there on my bucket list. I'd be happy to help implement a fix or test this, but at the moment I really don't know where to start.

Thanks!

**Comment by sergiovilar** [comment]
Is theres a way to enable the dvorak support by hand? I'm using a custom Dvorak layout and doesn't works.

**Comment by nathansobo** [comment]
You can try tossing this in your init script and see what happens.

```coffee
atom.keymaps.dvorakQwertyWorkaroundEnabled = true
```

**Comment by sergiovilar** [comment]
@nathansobo I've tried, doesn't works

**Comment by sergiovilar** [comment]
Could anyone help me here?

@nathansobo There's a possibility to made a patch to allow enable the dvorak support by hand? I've been reading the code, so I tried to create a custom keyboard layout with the same layout ID that Atom verifies, but without success.

**Comment by philoniare** [comment]
Thanks so much for implementing this. Dropping the following to the init script now works:
atom.keymaps.dvorakQwertyWorkaroundEnabled = true
Also applicable to dvorak based custom layouts such as Programming Dvorak

**Comment by GuidoSchmidt** [comment]
Thanks so much for this. Just made my life with atom on a Dvorak layout so much less frustrating :relaxed:

**Comment by sergiovilar** [comment]
I don't know why but I can't use my custom DVORAK-QWERTY with Atom anymore.

**Comment by aprowe** [comment]
I'm having the issue as well

**Comment by sergiovilar** [comment]
It seems the workaround for custom layouts has been removed:
https://github.com/atom/atom-keymap/pull/90#issuecomment-333520593

**Comment by sergiovilar** [comment]
@Ben3eeE this is the original issue, do you want me do add details on how to reproduce it here or should I create a new issue?

**Comment by Ben3eeE** [comment]
Hey!

I think it's better to open a new issue.
