### ISSUE TITLE
Requiring crashes in Electron 1.0.1

### ISSUE THREAD

**Issue by parisk** [atom/atom-keymap#134]
I am trying to use `atom-keymap` in an Electron app that I am building and it crashes. The version of Electron I am using is `1.0.1`.

I installed `atom-keymap@6.3.2` through my `package.json` file using Node `v4.3.2`, npm `3.8.0`, which were installed on my OS X El Capitan laptop using nvm `0.30.1`.

## Error
```
Uncaught Error: Module version mismatch. Expected 47, got 46.        ELECTRON_ASAR.js:158
```

## Application user agent
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) sourcelair-desktop/0.0.1 Chrome/49.0.2623.75 Electron/1.0.1 Safari/537.36
```

## package.json
```json
{
  "name": "sourcelair-desktop",
  "private": true,
  "version": "0.0.1",
  "main": "src/main.js",
  "dependencies": {
    "electron-prebuilt": "1.0.1",
    "dotenv": "2.0.0",
    "request": "2.72.0",
    "atom-keymap": "6.3.2"
  },
  "scripts": {
    "start": "./node_modules/.bin/electron ."
  }
}
```

## Screenshot
![image](https://cloud.githubusercontent.com/assets/1188592/15254497/c83c784c-193f-11e6-8eeb-0b20d2dc3e81.png)

**Comment by Montaldo** [comment]
Is this fixed already?

**Comment by nathansobo** [comment]
You need to rebuild the package's native dependencies against Electron. Check out this [document](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md)
