### ISSUE TITLE
ability to export keybinding to file

### ISSUE THREAD

**Issue by F-12** [atom/atom-keymap#135]
In the keybinding preference pane, i think it is good to export all the keybinding to a single file for later configuration use.
For an example scenario, i find all keybindings for cmd-k as follows,
![image](https://cloud.githubusercontent.com/assets/7236630/15427760/b8e8c3a2-1ec9-11e6-8266-063c45557ccd.png)
then i want to click a single button placed left of the input box or above the keybinding list called export button to export all keybindings in the list to a temporary file.
After some simple edition, i copy the content to my keymap.cson.
I think this will help me customize my keymap easily especially for atom keybinding hell.

**Comment by 50Wliu** [comment]
Please move this to the settings-view repo.  Thanks!
