### ISSUE TITLE
How to know how to phrase keymaps? 

### ISSUE THREAD

**Issue by jaepage** [atom/atom-keymap#140]
Both of these work. Why is that? What is the meaning of the first key?

```
'atom-workspace':
  'cmd-alt-2': 'pane:split-right'
```

```
'atom-text-editor':
  'cmd-alt-2': 'pane:split-right'
```

Atom v1.9.9
Mac OS v10.11.6 (El Capitan)

**Comment by mnquintana** [comment]
Please take a look at http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
