### ISSUE TITLE
Why do these keymaps collide? 

### ISSUE THREAD

**Issue by jaepage** [atom/atom-keymap#141]
If I enter these keymaps separately, they each work. But together, only the latter works. Why is that? 

```
'atom-text-editor':
  'cmd-alt-2': 'pane:split-right'

'atom-text-editor':
  'cmd-alt-3': 'pane:split-down'
```

(I've also tried with `atom-workspace`; same outcome. 

Atom v1.9.9
Mac OS v10.11.6 (El Capitan)

**Comment by mnquintana** [comment]
Please take a look at http://flight-manual.atom.io/using-atom/sections/basic-customization/#configuring-with-cson

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

**Comment by jaepage** [comment]
Thank you.
