### ISSUE TITLE
Cmd+backslash of JIS keyboard is regressed.

### ISSUE THREAD

**Issue by s-shin** [atom/atom-keymap#165]
I'm using JIS keyboard in Mac, but `cmd+\`, which can toggle tree view, isn't working fine in v1.11.2.
When I checked in v1.10.2 because I remembered it was working fine, it's certainly no problem.
I also tried v1.12.0-beta5 containing some fixes of key binding bug, but it's bugged yet.

Checked results:
- v1.10.2
  - Key binding resolver: `cmd-`
  - Working fine
- v1.11.2
  - Key binding resolver: `cmd-`
  - Not working
- v1.12.0-beta5
  - Key binding resolver: `cmd-¥`
  - Not working

NOTE: I swapped `¥` to `\` by [Google Japanese Input](https://www.google.co.jp/ime/). If didn't, we have to type `fn+¥` for `\`.

**Comment by nathansobo** [comment]
I've just published 1.12.0-beta7, which should fix this issue. Thanks for the report.

**Comment by s-shin** [comment]
Nice work!! Thank you for your prompt action.
