### ISSUE TITLE
Ctrl-Alt-[letter] keybinds don't work properly on ISO layout because of accented characters

### ISSUE THREAD

**Issue by Gutawer159** [atom/atom-keymap#175]
While using the ISO keyboard layout (on Windows - not sure whether this is an issue on other platforms), Ctrl-Alt-[letter] keybindings do not work properly sometimes, as ISO layout uses AltGr/Ctrl-Alt for accented characters, meaning that you cannot bind an action to something if it would produce an accented character, like for example `Ctrl-Alt-O` cannot be bound to because it resolves to `ó` - http://i.imgur.com/vSv4RgF.png. If I switch to US layout in the Windows settings, `Ctrl-Alt` keybindings work absolutely fine.

*Steps to reproduce:*
Switch the OS language in Windows to anything that is designed for the ISO layout - I used UK English to find this error, and try using a keybinding such as `Ctrl-Alt-O` - it should type `ó` into the text field, and not execute the action wanted.

**Comment by nathansobo** [comment]
This was deliberate. We had to take a stance on whether users should be allowed to enter accented characters or use certain bindings. Everyone seems to want something different.

**Comment by Ben3eeE** [comment]
The current system has a naive assumption that the accented character is always preferred which is not always true. for example for the ISO UK layout...

**Comment by kvaellning** [comment]
So, from a naive way of view this appears to be the same issue I ran into:

Switching to Atom 1.12.x and disabling the "keyboard-localization" package rendered stuff like adding a project folder with the `Ctrl-Alt-o` completely impossible.

I am using win10 german standard QWERTZ key-layout.

**Comment by Ben3eeE** [comment]
For core keybindings they should be revamped to not include <kbd>Ctrl-Alt-</kbd> variants on Windows to not run in to this issue. If you want <kbd>Ctrl-Alt-O</kbd> to still add project folder then you need to rebind it in your `keymap.cson`.

**Comment by kvaellning** [comment]
Okay, this one works, but seems a little bit counter-intuitive to add a custom keybinding which basically appears (from a quick glance) the same as the core keybinding:
[atom keybinding](https://www.dropbox.com/s/hv6xfvebrc5k3f4/atom%20keybinding.png?dl=0)

Changing `Ctrl-Alt-` variants on Windows may also run into issues for keybindings just like `Ctrl-Shift-o`, which triggers `application:open-folder`.

**Comment by nathansobo** [comment]
@damieng I still think a project to remap our `ctrl-alt-` bindings on Windows is a good idea.

**Comment by nathansobo** [comment]
@damieng should we reopen this until after merging a PR that updates all the package key bindings.

**Comment by nathansobo** [comment]
Also, until we make a change to `atom-keymap` things still won't work even if we clear the bindings out of the way.
