### ISSUE TITLE
Cannot input Chinese using Microsoft Pinyin

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom-keymap#177]
1. Switch input method to Microsoft Pinyin on Windows (this may also work with other Chinese input methods; I don't know)
2. Type some pinyin into the IME and select your choice

**Expected**: Chinese shows up in the editor
**Actual**: Nothing happens

In addition, I cannot activate the keybinding resolver while using Microsoft Pinyin, irregardless if I'm in Chinese or English mode.  Other shortcuts (Settings View, command palette, etc. work fine).
However if I activate it using a normal keymap before switching to Microsoft Pinyin the resolver shows `process` whenever the IME is active.

![no-chinese](https://cloud.githubusercontent.com/assets/2766036/20272602/6c6132d4-aa5c-11e6-93d9-5f7eb17c09a4.gif)

(In one of the previous gifs I recorded that I messed up in, it looked like the Chinese was briefly inserted and then almost immediately deleted)

Atom 1.14.0-dev-e2b4b69 (Electron 1.4.x branch), Windows 10 x64.  The gif is not in safe mode but I can reproduce it in safe mode as well.

**Comment by nathansobo** [comment]
@50Wliu Could you test out the build associated with atom/atom#13233 when you get a chance? It should fix this issue.

**Comment by ungb** [comment]
I tested it with the build on windows and now the chinese characters are being selected, but sometimes left over letters are added. Similar to #172 See gif here:
![chineseplayback](https://cloud.githubusercontent.com/assets/5624870/20335996/cd57d33e-ab7b-11e6-8cb6-cebd45eb25c8.gif)

Same behavior doesn't happen when typing on other editors.

**Comment by nathansobo** [comment]
@ungb Does the bug pictured above where the trailing `d` is appended occur on `1.11.x` or is this a `1.12.x` regression?
