### ISSUE TITLE
alt modifier with keyup triggers macOS alt-characters after partialMatchTimeout

### ISSUE THREAD

**Issue by oggy** [atom/atom-keymap#190]
I have the following functions:

```
atom.commands.add 'atom-text-editor', 'test-press', (event) ->
  event.preventDefault()
  event.stopPropagation()
  console.log 'test-press'

atom.commands.add 'atom-text-editor', 'test-release', (event) ->
  event.preventDefault()
  event.stopPropagation()
  console.log 'test-release'
```

Bound as follows:

```
'atom-text-editor':
  'alt-[': 'test-press'
  'alt-[ ^alt': 'test-release'
```

Now pressing and releasing `alt-[` fires the commands as expected, but if I keep alt held for a second, a [U+201C](http://www.fileformat.info/info/unicode/char/201C/index.htm) is also inserted (the standard Mac alt-character).

This does not happen if I remove the `test-release` binding, or if I use a different modifier.

Using macOS Sierra, with the US keyboard layout, and Atom 1.14.0-dev-0122b77 . This did not happen in 1.11.x (1.12.x and 1.13.x exhibited different erroneous behavior which seems mostly fixed -- just this issue remains).

**Comment by iolsen** [comment]
Thanks for the report! I'll investigate this week.

**Comment by iolsen** [comment]
✨ Great, detailed report here. I've reproduced the behavior in 1.13 and master. Looking at your PR now.

**Comment by oggy** [comment]
This problem is no longer happening as of 1.19 or 1.21-dev.
