### ISSUE TITLE
Multi keystroke keymap ends with `^` char enter partial match state unnecessarily.

### ISSUE THREAD

**Issue by t9md** [atom/atom-keymap#195]
Multi keystroke keymap ends with `^` char enter partial match state unnecessarily.

## Repro

- `keymap.cson`

```coffeescript
'atom-text-editor':
  'a b': 'editor:move-to-first-character-of-line'
  'a #': 'editor:move-to-first-character-of-line'
  'a ^': 'editor:move-to-first-character-of-line'
```

- Result
  - `a b`: dispatched immediately.
  - `a #`: dispatched immediately.
  - `a ^`: NOT dispatched immediately. Have to wait partial match timeout.

## Investigation

1. Add following observation code in you `keymap.cson`
2. invoke `user:observe-keymap-event` from command-palette.
3. Try `a b` and see chrome-dev console.log shows `hello` immediately.
4. Try `a #` and see chrome-dev console.log shows `hello` immediately. So no shift modifier issue.
5. Try `a ^` and see chrome-dev console.log shows `hello` **after** 1sec.

```coffeescript
atom.commands.add 'atom-text-editor',
  'user:hello': ->
    console.log 'hello'
  'user:observe-keymap-event': ->
    atom.keymaps.onDidPartiallyMatchBindings (event) ->
      {keystrokes, partiallyMatchedBindings} = event
      console.log keystrokes
      summary = partiallyMatchedBindings
        .map ({command, keystrokes}) -> "  " + keystrokes + " -> " + command
        .join("\n")
      console.log summary

    atom.keymaps.onDidMatchBinding (event) ->
      summary = event.keystrokes + " -> " + event.binding.command
      console.log "settled!: #{summary}"
      console.log "----------"
```

## What's the issues

- Single `^` seems to be treated as `keyup` modifier prefix.
- When keystroke was single `^`, it should be treated simple `keydown` keystroke of `^`. But it seems to be treated as keyup modifier prefix.
- To say simply `a b`, `a #`, `a ^` in this example should work exactly in same way.

## Investigation

Here is the console.log output of above `user:observe-keymap-event` with keymaps.

Maybe this function return `true` for single `^`?(Not confirmed with actual behavior just a quick look of code.)
https://github.com/atom/atom-keymap/blob/master/src/helpers.coffee#L248

##### keystorke: `a b`

- When `a` was keyupped(`^a`), there is three candidates.
- Just after `b` was typed, dispached to `user:hello`(displayed `hello`)

```
a
  a b -> user:hello
  a # -> user:hello
  a ^ -> user:hello
a ^a
  a b -> user:hello
  a # -> user:hello
  a ^ -> user:hello
hello
settled!: a ^a b -> user:hello
----------
```

##### keystorke: `a #`

- When `a` was keyupped(`^a`), there is three candidates.
- Just after `#` was typed, dispached to `user:hello`(displayed `hello`)

```
a
  a b -> user:hello
  a # -> user:hello
  a ^ -> user:hello
a ^a
  a b -> user:hello
  a # -> user:hello
  a ^ -> user:hello
hello
settled!: a ^a # -> user:hello
----------
```

##### keystorke: `a ^` (This is issue)

- When `a` was keyupped(`^a`), there is three candidates.
- But just after `^` was keyupped(`^^`), the remaining candidate is `a b`, and `a #`.(**NOTE `a ^` is dropped from candidate at this point**).
- After partial keymap timeout, settled to `a ^` then shows `hello`.

```
a
  a b -> user:hello
  a # -> user:hello
  a ^ -> user:hello
a ^a
  a b -> user:hello
  a # -> user:hello
  a ^ -> user:hello
a ^a ^
  a b -> user:hello
  a # -> user:hello
a ^a ^ ^^
  a b -> user:hello
  a # -> user:hello
a ^a ^ ^^ ^shift
  a b -> user:hello
  a # -> user:hello
a
  a ^ -> user:hello
a ^a
  a ^ -> user:hello
hello
settled!: a ^a ^ -> user:hello
```

## Real issue I'm facing.

I'm developing [vim-mode-plus](https://atom.io/packages/vim-mode-plus).
I have following keymap.
- `d 0`: is settled immediately
- `d ^`: is NOT. have to wait for partial match timeout. But there is no candidsate keymap exists other than single `^`.

```coffeescript
'atom-text-editor.vim-mode-plus.normal-mode':
  'd s': 'vim-mode-plus:delete-surround'
  'd s s': 'vim-mode-plus:delete-surround-any-pair'
  'd s S': 'vim-mode-plus:delete-surround-any-pair-allow-forwarding'

'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  '0': 'vim-mode-plus:move-to-beginning-of-line'
  '^': 'vim-mode-plus:move-to-first-character-of-line'
  'd': 'vim-mode-plus:delete'
```

**Comment by nathansobo** [comment]
@t9md Is this a regression in 1.13 or is it also a problem <= 1.12?

**Comment by t9md** [comment]
Yes. it seems happens when keyup modifier ^ is introduced. So its should be started long before.

**Comment by nathansobo** [comment]
Thanks for fixing it!
