### ISSUE TITLE
Polish letters - not work

### ISSUE THREAD

**Issue by ziemowitpl** [atom/atom-keymap#208]
### Description

Missing Polish keys "ó", "ż"

### Steps to Reproduce

1. [First Step] alt + o
2. [Second Step]alt + z

**Expected behavior:** Write "ó", "ź"

**Actual behavior:** 
alt + o - open window "Open Folder"; 
alt + z - open window "Atom" [write:" Confirm Checkout HEAD Revision"]

### Versions
1,12.9

### Version
1.13.0 Wotk 👍 
Thx 🥇

**Comment by Ben3eeE** [comment]
This has already been fixed in Atom 1.13 ✨
