### ISSUE TITLE
Won't install on Windows

### ISSUE THREAD

**Issue by sgehrman** [atom/atom-keymap#210]
Never had a problem installing packages, but this one doesn't work.

$ npm install atom-keymap --save-dev
npm WARN prefer global coffee-script@1.9.0 should be installed with -g

> runas@3.1.1 install f:\Github\electron-store\node_modules\runas
> node-gyp rebuild

f:\Github\electron-store\node_modules\runas>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "c:\Users\Steve\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:111:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd f:\Github\electron-store\node_modules\runas
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
store@1.0.0 f:\Github\electron-store
+-- clear-cut@2.0.1  extraneous
+-- keyboard-layout@2.0.10  extraneous
`-- season@5.4.1  extraneous

npm WARN store@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "atom-keymap" "--save-dev"
npm ERR! node v7.3.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     f:\Github\electron-store\npm-debug.log

**Comment by 50Wliu** [comment]
You need Python 2.7 installed at `C:\Python27`, or to point the `PYTHON` env var where you installed it.

**Comment by sgehrman** [comment]
I have Python.  Why do I have to setup this ENV?

**Comment by 50Wliu** [comment]
Because node-gyp looks for it there.

> gyp ERR! stack Error: Can't find Python executable "c:\Users\Steve\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
> gyp ERR! stack at PythonFinder.failNoPython (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)

**Comment by sgehrman** [comment]
I don't know how to do that.  Your docs need to include this.  Thanks.

On Jan 26, 2017 6:39 PM, "Wliu" <notifications@github.com> wrote:

Because node-gyp looks for it there.

gyp ERR! stack Error: Can't find Python executable
"c:\Users\Steve\AppData\Local\Programs\Python\Python36-32\python.EXE", you
can set the PYTHON env variable.
gyp ERR! stack at PythonFinder.failNoPython (c:\Program
Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/atom/atom-keymap/issues/210#issuecomment-275576137>,
or mute
the thread

**Comment by 50Wliu** [comment]
As far as I can determine, we don't have docs on how to install atom-keymap?  It's mostly for internal Atom usage, so there was never a need for installation docs.

[This](http://superuser.com/a/284351) superuser goes into pretty nice detail about how to set environment variables on different platforms.
