### ISSUE TITLE
Keymap: Missing key binding for rendering Python graph with matplotlib in Atom

### ISSUE THREAD

**Issue by defaultUser212** [atom/atom-keymap#220]
Hey,

on Mac OS X there is no possibility to render python coded graphs with matplotlib in Atom. On Windows you can do this with ctrl+shift+enter within Atom itself. The reason why this doesn't work is a missing key binding für Linux and OS X.

**Comment by Ben3eeE** [comment]
@defaultUser212 This looks like a problem with the package you are using to render python coded graphs and not with `atom-keymap`. You should open this issue on their repository.

The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
