### ISSUE TITLE
Remove number pad support?

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom-keymap#42]
Currently number pad keys are generated with a `num-` prefix to distinguish whether the key was pressed on the main keyboard or the number pad section.

This gives people more precision in their keybindings but comes at a cost, if an Atom package adds a `ctrl-left` keybinding and a person presses `ctrl` and `4` on the number pad with `NumLock` enabled, the key maps to `ctrl-num-left` and that package's command isn't triggered. People seem to be expecting number pad keys with num lock pressed to behave without distinction from their non-number pad equivalents as evidenced in https://github.com/atom/atom/issues/2931

This affect any keybindings that use `Home`, `End`, `PageUp`, `PageDown`, `Enter`, `+`, `-`, `/`, `*`, `left`, `right`, `up`, and `down`.  They all require keybindings for their command with the `num-` modified to target this case.

It seems like a burden on package authors to even force them to consider the number pad and num lock when coming up with keybindings.

Some options:
- Retry the keystroke without the `num-` modifier if no matches with the `num-` modifier exist.
- Remove support for the `num-` modified completely.
- Something else?

/cc @nathansobo and @jacobgardner

**Comment by ujLion** [comment]
With numpad on - I would like to see "Shift+7(Home)" resolve to 'Home' : move to first character in line.
However I am unable to map this using the keymap. This works fine in windows otherwise like in the notepad.

**Comment by ujLion** [comment]
On a compact keyboard like that of a laptop - it is a real pain to not have numpad support.
When numpad(num lock) is on, in order to use the 'home' key I need to first turn off numpad and then press the home key. When it is supposed to simply work in conjunction with the 'shift' key, e.g. as it is in 'notepad'.

**Comment by ujLion** [comment]
Keeping things as it is, please map shift combinations of the numpad with the alternate functionality.
E.g. 7 > Home, 9 > PgUp and so on..
Should I file this as a separate bug?

**Comment by J-Kappes** [comment]
So, there's no way to bind to numpad buttons now?
I'm trying to use ctrl-shift-numpadDirections to split panes.
