### ISSUE TITLE
Shortcut labels not updating

### ISSUE THREAD

**Issue by Mottie** [atom/atom-keymap#50]
I installed a package and I wanted to swap the keymapping.

When I open the command palette, the shortcut labels still show up as if the bindings are still applied

![shortcut](https://cloud.githubusercontent.com/assets/136959/4347133/6a31b416-4136-11e4-8c2e-f88e844f0d1f.png)

**Comment by kevinsawicki** [comment]
This library is for the atom-keymap standalone keybindings library, this looks like an issue with Atom's core command registry.

Would you mind reopening this on https://github.com/atom/atom if you are still seeing it happen in Atom 1.0.3?

**Comment by Mottie** [comment]
Thanks, it looks like it was fixed, or actually I think the problem was I was using a lower-case `t`.

This works:

```
'.atom-workspace':
    'ctrl-shift-T' : 'unset!'
    'ctrl-shift-T' : 'atom-terminal:open-project-root'
    'alt-shift-T'  : 'unset!'

```
