### ISSUE TITLE
Atom Should be able to map keybindings to the fn key on Macs

### ISSUE THREAD

**Issue by TSiege** [atom/atom-keymap#54]
I'm not sure if I'm doing this wrong, but I haven't been able to rebind the `fn` key on my Mac, so I can use `fn-cmd-delete` to delete to the end of a line.  It seems to only delete to the beginning of the line.

**Comment by thedaniel** [comment]
Unfortunately, the mac's `fn` key doesn't trigger a keypress event in Atom (or Chrome), and at a quick glance something like `fn-z` looks exactly the same as `z` in the console, so this is not likely to be fixed. I'm not saying it's impossible, but unless my (admittedly shallow) investigation was missing something, it would involve something like patching chromium within Electron, if it's even possible.

Can you bind that key in that way in other applications on your mac? I'm going to close this based on my investigation but if other apps can do it, you can reopen this.
