### ISSUE TITLE
Keybinding targetting node inside a shadow DOM

### ISSUE THREAD

**Issue by abe33** [atom/atom-keymap#66]
I'm not sure whether this is a bug or a limitation of shadom DOM but I can't find a way to trigger a command on an element in a shadow root.

Here's my use case: I have a custom element to edit a table, which use a shadow DOM for its content, I also have an `atom-text-editor` element used for editing the cell's content that is contained inside the shadow root (seems like the only way to make it render properly). I would like to remap some editor's commands to make it feel more natural for users (the editor is multiline but enter should trigger a confirmation, and ctrl-enter a new line insertion for instance).
It turns out that using the following keymap doesn't trigger the expected command on the text editor element: 

```cson
'atom-table-editor::shadow atom-text-editor':
  'enter': 'core:confirm'
  'ctrl-enter': 'editor:newline'
```

Is there a way to workaround this issue? 
Is it something that can be workaround?

I haven't looked at the keymap implementation in detail, but if it use the `matches` method I can say that it doesn't reach nodes inside a shadow root.

Here's a sample of a test in the console that demonstrates that matches doesn't work with shadow root:
```
> e = atom.views.getView(atom.workspace.getActiveTextEditor())
<atom-text-editor class=​"editor" tabindex=​"-1" callattachhooks=​"true" data-grammar=​"source coffee" data-encoding=​"utf8">​…​</atom-text-editor>​
> g = e.shadowRoot.querySelector('.indent-guide')
<span class=​"leading-whitespace indent-guide invisible-character">​··​</span>​
> g.matches('atom-text-editor::shadow .indent-guide')
false
> g.matches('.indent-guide')
true
```

What approach would you consider for this use case?

FWIW the code of the original space-pen version can be found here: https://github.com/abe33/atom-table-edit/blob/master/lib/table-view.coffee#L761-L777
And the WIP version using custom element is there: https://github.com/abe33/atom-table-edit/blob/master/lib/table-view.coffee#L761-L777

**Comment by nathansobo** [comment]
Have you considered putting the nested element into the light DOM with a content insertion point (`<content>` tag)? There's an article about it [here](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-301/)

If the element remains in the light DOM, the event path doesn't cross the shadow boundary conceptually. If `matches` doesn't cross the shadow boundary then we're out of luck for selectors containing `::shadow`, but considering that the shadow DOM is meant to be an abstraction boundary that masks implementation, it sort of makes sense. Would be interested if an insertion point would give you the behavior you need.

**Comment by abe33** [comment]
@nathansobo Thanks for the link, I was wondering if light DOM and shadow DOM could cohabit in a same node. Initially that's what I intended to do, I just lacked the knowledge :). 

Thanks again, I'll close this issue now.
