### ISSUE TITLE
[Feature Request] Unindent keybind

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom-keymap#68]
Either I'm blind or there is no keybind to unindent a line in Atom like there is in for example Sublime. Would be nice if that could be added :)

**Comment by kevinsawicki** [comment]
There is an outdent command that is bound (on mac) to `cmd-[` and `shift-tab`, is this not what you are looking for?

**Comment by 50Wliu** [comment]
Do you mean something like <kbd>Shift</kbd>+<kbd>Tab</kbd>?
Ah, looks like you beat me to it @kevinsawicki :P 
Shift Tab works on Ubuntu and Windows too (Ctrl+[ on non-Mac).

**Comment by Stanzilla** [comment]
Oh god. I always looked for "unindent" instead of "outdent" because that's how it is called in ST. Yep, that works like a charm, thanks guys!
