### ISSUE TITLE
Keymap Is Not Reloaded If keymap.cson Consists Solely Of Comments

### ISSUE THREAD

**Issue by joefitzgerald** [atom/atom-keymap#69]
Suppose I define the following in my `keymap.json` file:

```cson
'atom-text-editor:not(mini).autocomplete-active':
  'tab': 'unset!'
  'enter': 'autocomplete-plus:confirm'
  'up': 'unset!'
  'down': 'unset!'
  'ctrl-p': 'autocomplete-plus:select-previous'
  'ctrl-n': 'autocomplete-plus:select-next'
```

And then I decide that I don't want to do that, so I comment it all out:

```cson
# 'atom-text-editor:not(mini).autocomplete-active':
#   'tab': 'unset!'
#   'enter': 'autocomplete-plus:confirm'
#   'up': 'unset!'
#   'down': 'unset!'
#   'ctrl-p': 'autocomplete-plus:select-previous'
#   'ctrl-n': 'autocomplete-plus:select-next'
```

If _I have no other cson content_, then I believe (according to https://github.com/atom/atom-keymap/blob/13b53508fcf0d52e430c937a27bcaea5909ec39f/src/keymap-manager.coffee#L375-L384) the keymap won't actually get reloaded.

I.e. If i only have one definition in my keymap and I wish to unset it by commenting it out, I have to quit and relaunch Atom.

If a keymap file cannot be loaded, atom should still invalidate any prior keymap associated with that file.

**Comment by ythej** [comment]
Hi,
I want to work on this bug. I am newbie here. Could anyone please help me to start with.
Thank you.

**Comment by nathansobo** [comment]
@ythej We already watch the user's keymap and reload it when it changes on disk. There's likely an error when the file has only commented content, causing us to abort entirely. We could go ahead unload the existing keymap even when there is an error, or we could detect the case where everything is commented and handle it specially.

To get started, you'll want to clone a copy of this package and start running its package specs. Add a failing spec to the relevant location where we're probably already testing the change detection, then fix the problem and open a PR.

**Comment by ythej** [comment]
@nathansobo , Yeah, I am already done with build environment. I will try it and get back to you if any doubts.

Thank you.

**Comment by ythej** [comment]
@nathansobo , I am sorry if it is really basic. I am using this steps to open keymap:
1> `ctrl-shift-p`
2> open `Application: Open your keymap`

Is it where we edit the keymap or we should edit in the keymap/linux.cson ?
Thank you.
