### ISSUE TITLE
Bundled prefixed keys bindings delay even if 'unset!' by user keymap

### ISSUE THREAD

**Issue by peterwmwong** [atom/atom-keymap#78]
This affects keybindings like `cmd-k`, where `cmd-k` is the prefix of many keybindings that come bundled with Atom.   Hitting `cmd-k` has a delay **even if every single one of these keybindings are `unset!`** in the user key map.  

Doing some debugging, in the dev tools. What appears to be happening is this...

Putting a breakpoint on line 440 of `keymap-manager.js` (where partial matches are found)...
![screen shot 2015-04-21 at 9 30 58 pm](https://cloud.githubusercontent.com/assets/284734/7266369/0633f822-e86e-11e4-8928-e6f1cb9f5de5.png)
... and hitting `cmd-k` to hit our breakpoint, we see that the `partialMatchCandidates` array being filtered will iterate over the bundled keymap bindings **BEFORE** the user bindings.   The console in the screenshot above, shows the `source` of all the keybindings of `partialMatchCandidates`.  As you can all the bindings from `/Application/Atom.app/*` are at the top, while the user bindings from `/Users/*` are on the bottom. This ordering allows line 444 of `keymap-manager.js` to be reached, which incorrectly identifies it as a partialMatch even though a user specified keymap binding has it `unset!`.

A naive fix that simply reverses the order of `partialMatchCandidates` (process bundled bindings **AFTER** user bindings)...
![screen shot 2015-04-21 at 9 39 43 pm](https://cloud.githubusercontent.com/assets/284734/7266421/f6fb02f0-e86e-11e4-913f-19bdc76f5bb2.png)
...correctly yields an empty `partialMatches` as all user bindings are added to the `ignoreKeystrokes` set and all the bundled key bindings are then ignored.

@stmichael mentioned this behavior on a different issue [#49](https://github.com/atom/atom-keymap/issues/49#issuecomment-69179091)

**Comment by peterwmwong** [comment]
Simply flipping the order is probably not the correct fix.  Maybe first adding all the `unset!` bindings to the `ignoreKeystrokes` set, before filtering?

**Comment by ilyashubin** [comment]
+1. Would be nice to have a way to remove this delay somehow

**Comment by meleyal** [comment]
+1

**Comment by birbird** [comment]
+1
