### ISSUE TITLE
Mac: `control+up` setting for mission control 

### ISSUE THREAD

**Issue by austinpray** [atom/atom-keymap#8]
1. Using Atom Version 0.79.0 (0.79.0)
2. I set my settings like this: 
   ![screenshot 2014-03-29 14 38 11](https://cloud.githubusercontent.com/assets/2192970/2559396/affd99c0-b779-11e3-9967-d1fec7940abf.png)
   Where mission control activates with `control+up`
3. Keyboard shortcut for `Add Selection Above` in Atom is `control+shift+up`.
4. _Expected behavior:_ Atom's shortcut takes precedence  
   _What I got:_ mission control activates and plays in slow motion (when you hold shift + some native animation it plays in slow motion).
5. Note: Keybinding resolver reads: `ctrl-shift-shift` when it should read `ctrl-shift-up`

There might not be a way around this. The solution I came up with was just to change the binding for mission control to `f4`, as I do not use it much anyway.

**Comment by PeterEmil** [comment]
I changed my shortcut mappings for Mission Control to take use of the expanded keyboard, so they are all in the range of F16 to F19. That seems to work flawless.
