### ISSUE TITLE
Identical selectors in user keymaps file appear to overwrite previous ones in that file

### ISSUE THREAD

**Issue by crucialfelix** [atom/atom-keymap#81]
I am having very strange behavior with a keybinding. Its a bug, but hard to pin it down.

I think it has to do with having multiple blocks in keymaps with the same selector.
The following ones overwrite the previous ones.  
I assumed that I could group things by functionality or package and they would add like css.

I'm trying to assign:

    shift-cmd-R => Symbols View : Toggle Project Symbols

Emmet has that registered:

```
'.platform-darwin atom-text-editor:not([mini])':
  'shift-cmd-R': 'emmet:reflect-css-value'
```

So my keymaps file claims it:

```
# toggle project symbols
'.platform-darwin atom-text-editor':
  'shift-cmd-R': 'symbols-view:toggle-project-symbols'
'.platform-darwin atom-text-editor:not([mini])':
  'shift-cmd-R': 'symbols-view:toggle-project-symbols'
```

but further down I had another identical block:

```
'.platform-darwin atom-text-editor:not([mini])':
  'ctrl-!': 'move-panes:move-left'
  'ctrl-@': 'move-panes:move-right'
```

Now emmet still intercepts. Keybindings Resolver shows emmet:reflect-css-value as top hit and doesn't show my registered one at all.

When I do `shift-command-P` (command palette) and search for toggle-project-symbols it shows the key command as `shift-cmd-R`. When I search in keybindings I see my User registration with the key command.

But it doesn't appear to be really registered.

What was also strange is that once I invoked it with command-palette and then shift-cmd-R worked for a while ! and then went away. I swear I didn't change my keymaps file, but somehow something internal to the keymaps system got rewritten.

I rearranged my keymaps file to group all definitions by the selector and the problem went away.

**Comment by izuzak** [comment]
> I rearranged my keymaps file to group all definitions by the selector and the problem went away.

You're seeing expected behavior here. If you have 

```
'.platform-darwin atom-text-editor:not([mini])':
  'shift-cmd-R': 'symbols-view:toggle-project-symbols'

'.platform-darwin atom-text-editor:not([mini])':
  'ctrl-!': 'move-panes:move-left'
  'ctrl-@': 'move-panes:move-right'
```

then what you're doing is assigning two different values to the same key `.platform-darwin atom-text-editor:not([mini])`, so one value overwrites the other. 

Basically, you're doing this:

```
var selector = ".platform-darwin atom-text-editor:not([mini])";

var keymaps = {};

keymaps[selector] = {
    "shift-cmd-R": "symbols-view:toggle-project-symbols"
};

keymaps[selector] = {
    "ctrl-!": "move-panes:move-left",
    "ctrl-@": "move-panes:move-right"
};
```

Does that explain things? Also, see https://github.com/atom/snippets/issues/72 for a suggestion on how to let users know that this is happening.

**Comment by izuzak** [comment]
> What was also strange is that once I invoked it with command-palette and then shift-cmd-R worked for a while ! and then went away. I swear I didn't change my keymaps file, but somehow something internal to the keymaps system got rewritten.

If you could provide exact steps to reproduce problematic behavior -- that would be helpful. Also notice that `shift-cmd-r` is a [default keybinding for the Symbols View package](https://github.com/atom/symbols-view/blob/57aa6b4093ccd7d8db150b6b996b58705839e7e4/keymaps/symbols-view.cson#L15), so there's no need to define it in your local keymap file. Not sure if I missed anything in your description.

**Comment by crucialfelix** [comment]
OK, fair enough. I should've realized that of course it isn't a .css file, its .cson

thanks!

> Also notice that shift-cmd-r is a default keybinding for the Symbols View package, so there's no need to define it in your local keymap file.

Because emmet grabs it first, I have to use my powers as User to redefine it for symbols view. In fact emmet does it even for python files which is IMO wrong.

Keybindings are still a bit frustrating to work with TBH. The selectors are a great way to implement keybindings, but its not fun to write them out manually.

Maybe some package could provide an interactive interface and would write the keymaps.cson for us. Something that combines Key binding resolver, Show keybindings, show what language scopes they are active in, can learn key strokes, click to select which one should get priority etc.

thanks again

**Comment by izuzak** [comment]
> Because emmet grabs it first, I have to use my powers as User to redefine it for symbols view. In fact emmet does it even for python files which is IMO wrong.

Ahhh, I totally forgot about that while I was writing the last part of the comment -- sorry.

> Keybindings are still a bit frustrating to work with TBH.

Yeah, I get what you're saying -- that's good feedback. There's also https://github.com/atom/atom/issues/6718, so you might consider adding a comment there with some things which you found problematic (and the package idea you described as well, so that it's not lost). I think that would be helpful.
