### ISSUE TITLE
Multiple commands for one keystroke

### ISSUE THREAD

**Issue by xlaywan** [atom/atom-keymap#84]
Separated by comma:
``` cson
'up': 'autocomplete-plus:cancel, core:move-up'
'down': 'autocomplete-plus:cancel, core:move-down'
```

**Comment by lee-dohm** [comment]
You can create a composed command using this technique from the documentation:

https://atom.io/docs/latest/behind-atom-keymaps-in-depth#composed-commands

**Comment by xlaywan** [comment]
Thank you!

**Comment by lee-dohm** [comment]
It sounds like this took care of your issue. If you have any more questions, please let us know! In the meantime, I'm going to close this :grinning:

**Comment by ricardovsilva** [comment]
Since atom docs has changed, url to composed commands has changed too.
New url is http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#composed-commands

**Comment by JobJob** [comment]
Having created a couple of custom commands myself, I think it would be great if users weren't required to understand the implementation details of each command they want to compose. Some sort of simple composition syntax like the one in the OP would be great.

Not sure what would be involved in implementing this, is it very complex with the way the keymap system is designed?

**Comment by Sirfrummel** [comment]
I see in composed commands it shows an example of creating a custom shortcut.  I am trying to do that, but how I do specify the editor commands now?  I want to do:
`hey-pane:toggle-focus-of-active-pane` and `Tree View: Toggle` ?

**Comment by lawrence-dol** [comment]
This issue has bugged me. I finally wrote a couple little helpers into my init script to make creating and registering compound commands easy.

````
function addEditorCommand(nam,fnc) {
    atom.commands.add("atom-text-editor", "custom:"+nam,(evt) => {
        if(!atom.workspace.getActiveTextEditor()) { return; }
        fnc(evt);
        });
    }

function multicmd(...cmds) {
    return (evt) => {
        cmds.forEach((cmd) => { atom.commands.dispatch(evt.target,cmd); });
        };
    }

addEditorCommand("multi-cursor-mark-and-move-down"   , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-down"));
addEditorCommand("multi-cursor-mark-and-move-to-eol" , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-to-end-of-line"));
addEditorCommand("multi-cursor-mark-and-move-to-sol" , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-to-first-character-of-line"));
addEditorCommand("multi-cursor-mark-and-move-left"   , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-left"));
addEditorCommand("multi-cursor-mark-and-move-right"  , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-right"));
addEditorCommand("multi-cursor-mark-and-move-up"     , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-up"));

let normalizeWhitespace = multicmd("whitespace:convert-all-tabs-to-spaces", "whitespace:remove-trailing-whitespace", "line-ending-selector:convert-to-LF", "core:save");
addEditorCommand("normalize-whitespace",normalizeWhitespace);
atom.workspace.onDidAddTextEditor=(evt) => {
    normalizeWhitespace(evt);
    }

addEditorCommand("scroll-up"        , multicmd("ctrl-dir-scroll:scroll-up","core:move-up"));
addEditorCommand("scroll-down"      , multicmd("ctrl-dir-scroll:scroll-down","core:move-down"));
addEditorCommand("scroll-jump-up"   , (evt) => {
    for(xa=0; xa<50; xa++) { atom.commands.dispatch(evt.target,"custom:scroll-up"); }
    });
addEditorCommand("scroll-jump-down" , (evt) => {
    for(xa=0; xa<50; xa++) { atom.commands.dispatch(evt.target,"custom:scroll-down"); }
    });
````

**Comment by matt81093** [comment]
@lawrence-dol Somewhat random, but any clue why MultiCD wouldn't work in coffeescript form?

**Comment by lawrence-dol** [comment]
@matt81093 : No idea at all. Sorry.

**Comment by Mikami382** [comment]
This is no longer working, I can't run 2 actions seperated by comma.
`'.platform-win32 atom-workspace, .platform-linux atom-workspace':
  'ctrl-1': 'core:save,platformio-ide-terminal:insert-custom-text-1'
`

**Comment by Mikami382** [comment]
> This issue has bugged me. I finally wrote a couple little helpers into my init script to make creating and registering compound commands easy.
> 
> ```
> function addEditorCommand(nam,fnc) {
>     atom.commands.add("atom-text-editor", "custom:"+nam,(evt) => {
>         if(!atom.workspace.getActiveTextEditor()) { return; }
>         fnc(evt);
>         });
>     }
> 
> function multicmd(...cmds) {
>     return (evt) => {
>         cmds.forEach((cmd) => { atom.commands.dispatch(evt.target,cmd); });
>         };
>     }
> 
> addEditorCommand("multi-cursor-mark-and-move-down"   , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-down"));
> addEditorCommand("multi-cursor-mark-and-move-to-eol" , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-to-end-of-line"));
> addEditorCommand("multi-cursor-mark-and-move-to-sol" , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-to-first-character-of-line"));
> addEditorCommand("multi-cursor-mark-and-move-left"   , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-left"));
> addEditorCommand("multi-cursor-mark-and-move-right"  , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-right"));
> addEditorCommand("multi-cursor-mark-and-move-up"     , multicmd("multi-cursor-plus:mark", "multi-cursor-plus:move-up"));
> 
> let normalizeWhitespace = multicmd("whitespace:convert-all-tabs-to-spaces", "whitespace:remove-trailing-whitespace", "line-ending-selector:convert-to-LF", "core:save");
> addEditorCommand("normalize-whitespace",normalizeWhitespace);
> atom.workspace.onDidAddTextEditor=(evt) => {
>     normalizeWhitespace(evt);
>     }
> 
> addEditorCommand("scroll-up"        , multicmd("ctrl-dir-scroll:scroll-up","core:move-up"));
> addEditorCommand("scroll-down"      , multicmd("ctrl-dir-scroll:scroll-down","core:move-down"));
> addEditorCommand("scroll-jump-up"   , (evt) => {
>     for(xa=0; xa<50; xa++) { atom.commands.dispatch(evt.target,"custom:scroll-up"); }
>     });
> addEditorCommand("scroll-jump-down" , (evt) => {
>     for(xa=0; xa<50; xa++) { atom.commands.dispatch(evt.target,"custom:scroll-down"); }
>     });
> ```

tried to convert this to coffescript, no luck

```addEditorCommand = (nam, fnc) ->
    atom.commands.add 'atom-text-editor',
      'custom:ctrl-1': (evt) ->
          #editor = @getModel()
          #editor.insertText(new Date().toLocaleString())
          if (!atom.workspace.getActiveTextEditor())
              return
          fnc(evt)

multicmd = (cmds...) ->
    return (evt) -> cmds.forEach((cmd) -> atom.commands.dispatch(evt.target, cmd))

addEditorCommand("ctrl-1", multicmd("core:save"))```
