### ISSUE TITLE
Cant delete/modify included shortcut

### ISSUE THREAD

**Issue by radek024** [atom/atom-keymap#86]
Hi guys, i am Radek and i from Poland. Nice to meet GitHub communty! 

Well, my english is not well(as I would like ;) ), but I would like to tell you about my problem with shortcut - I cant delete and modify Atom shortcut - in Polish languague is some letters like ó - it is make by alt+o, or ś - alt+s. 

Some parts of shortcuts have the same keys, well its annoying when I would like to fill up my web project with polish chharacters. I tried to modify win32.json like delete line with shortcut or just delete the command and put "unset!". That not working. Every time i try to do it, i save that file.

I have no idea what can be wrong. 

Thanks in advance! 
Radek.

**Comment by 50Wliu** [comment]
Duplicate of #35 and #37, please subscribe there for updates.
