### ISSUE TITLE
Cannot override default keybinding

### ISSUE THREAD

**Issue by stevepm** [atom/atom-keymap#88]
Hi, I'm trying to use cmd-delete to delete the whole line.

In my keymap.cson, I have this:

'atom-text-editor':
  'cmd-delete': 'editor:delete-line'

But, the original cmd-delete which is bound to 'editor:delete-to-end-of-line' is taking authority over my defined binding.

![screen shot 2015-06-30 at 16 35 49](https://cloud.githubusercontent.com/assets/431557/8444495/185e9764-1f46-11e5-871d-4174f4c75886.png)

Any ideas on how to fix this?

**Comment by stevepm** [comment]
I also just tried adding this:
'atom-text-editor':
  'cmd-delete': 'unset!'

But nothing changed.

**Comment by nathansobo** [comment]
@stevepm Did you try using your binding with the keybinding resolver active? User bindings should take precedence because they're loaded later. Would be interested to see what shows up in the resolver.

**Comment by stevepm** [comment]
Welp, figured out my problem.

I needed to map cmd-backspace instead of cmd-delete (on a mac), in order to user the delete key.

Thanks @nathansobo for the suggestion, that helped me fix it.
