### ISSUE TITLE
Overriding keybindings

### ISSUE THREAD

**Issue by maveonair** [atom/atom-keymap#9]
Currently it is not possible to override keybindings, instead you add additional keybindings for a package's keybindings in your own keymap definitions. 

For example: 
It is a really pain when you are using Git-Diff with the Swiss-German (French, etc) keyboard layout because "alt-g" is mapped to "@". The issue is that you always have to type "alt-g" twice to get the "@" and this is not really usable IMHO: https://github.com/atom/git-diff/issues/15

**Comment by fgimian** [comment]
I'm really struggling with this, been playing with it for an hour and simply can't get it to work.

A simple scenario, let's say I want to disable ctrl+d.  I have added this to my keymap.cson file:

```
'.platform-win32 atom-text-editor, .platform-linux atom-text-editor':
  'ctrl-d': 'unset!'
```

The resolver picks it up but as you can see, the keyboard shortcut is still taking effect:

![image](https://cloud.githubusercontent.com/assets/1811813/7781536/fa08176c-0132-11e5-9fc5-f9003c79e1cb.png)

I have attempted this with various other shortcuts too and experienced the same problem.  I re-read the docs several times too and honestly think I'm doing it correctly.

What am I missing? :smile: 
Fotis

**Comment by nathansobo** [comment]
There were issues unsetting bindings that also appeared in the application menu, as discussed in #79. That issue should be resolved and fixed in 0.203.0.

**Comment by thebarty** [comment]
Hi guys,

I am having problems with this using 1.12.6. The default-action is still run, after overwriting it in keymap.cson.

Example:
When trying to assign "cmd-b" to a different command (see below), the default-behaviour ("fuzzy-finder:toggle-buffer-finder") is still run.

This is what my keymap.cson looks like:

```
'atom-text-editor':
  # 'cmd-b': 'unset!'  # will NOT work
  'cmd-b': 'tree-view:toggle'  # will NOT get rid of "fuzzy-finder:toggle-buffer-finder"-default
```

Any suggestions, how to get rid of the double-action-trigger?

**Comment by Ben3eeE** [comment]
@thebarty I believe you need to use the correct selector when unsetting the keybinding. See http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#removing-bindings

If you have more questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by thebarty** [comment]
Hmmm... I don't quite get it... this one here does NOT work:

```
'tree-view':  # '.tree-view' does NOT work either
  ':toggle': 'unset!'  #   'toggle': 'unset!' does NOT work either

'atom-text-editor':
  'cmd-b': 'tree-view:toggle'
  'cmd-e': 'editor:delete-line'
```

**Comment by Ben3eeE** [comment]
I am not really clear on what you want to achieve. If you want <kbd>cmd-b</kbd> to toggle the `tree-view` try using the `atom-workspace` selector:

```
'atom-workspace':
  'cmd-b': 'tree-view:toggle'
```

**Comment by thebarty** [comment]
YEAH MAN - thats the one!!!! "fuzzy-finder:toggle-buffer-finder" is NOT double-triggered anymore.

Thanks a lot. It already feels much better! 👍
