### ISSUE TITLE
Cannot trigger binding for "shift+;" or ":" on OS X's Dvorak - Qwerty ⌘ layout

### ISSUE THREAD

**Issue by jsonnull** [atom/atom-keymap#93]
In OS X's Dvorak - Qwerty ⌘ layout, I have the following keybinding:

``` coffeescript
'atom-text-editor.vim-mode:not(.insert-mode)':
  ':': 'ex-mode:open'
```

or

``` coffeescript
'atom-text-editor.vim-mode:not(.insert-mode)':
  'shift+;': 'ex-mode:open'
```

Both fail to open the desired command when using the Dvorak - Qwerty ⌘ layout, but succeed when plain Dvorak layout is in use.

**Comment by UltCombo** [comment]
See https://github.com/atom/keybinding-resolver/issues/28 and https://github.com/atom/atom-keymap/issues/37

**Comment by nathansobo** [comment]
We have a custom workaround in place for issues on Dvorak-Qwerty. There may be a hole in our ad-hoc adjustments to key events. If someone is interested in investigating it, these would be the following steps:

* Get a local build of Atom
* Clone the `atom-keymap` repo
* `npm link` in the `atom-keymap` repo and `npm link atom-keymap` in the Atom build
* Run in dev mode
* Insert a breakpoint (`debugger`) or `console.log` and figure out where we go wrong.
