### ISSUE TITLE
Idea: keymap prefixes as CSON keys

### ISSUE THREAD

**Issue by art-solopov** [atom/atom-keymap#98]
Here's a part of my `keymaps.cson`:
```coffeescript
'atom-workspace':
  'alt-r c': 'rails-transporter:open-controller'
  'alt-r v': 'rails-transporter:open-view-finder'
  'alt-r m': 'rails-transporter:open-model'
# Et cetera
```

Here's what I'd like to be able to do:
```coffeescript
'atom-workspace':
  'alt-r':
    'c': 'rails-transporter:open-controller'
    'v': 'rails-transporter:open-view-finder'
    'm': 'rails-transporter:open-model'
```

**Comment by izuzak** [comment]
Can you also explain _why_ you'd like to be able to do this, what would be the potential benefits, and if you see any problems with this approach? (E.g. would it impact readability)

I think including such details with requests like these is helpful.

**Comment by art-solopov** [comment]
@izuzak The reasons why I'd like to do this would be:
1. Less keystrokes;
2. The ability to override a prefix with one change (i. e., if I want to start `rails-transporter` commands with `ctrl-r` instead of `alt-r`, I'll only have to change one line of CSON).

The potential drawback I see is mixing atom selectors (e. g. `atom-workspace`) with key selectors (`alt-r`).

**Comment by nathansobo** [comment]
This isn't something I want to do. It is a bit more convenient but it also adds complexity, and the less complexity the better from a maintenance perspective. Thanks for sharing the idea though.
