### ISSUE TITLE
Not possible to overwrite the grammar selector

### ISSUE THREAD

**Issue by thibmaek** [atom/atom-keymap#99]
I overwrote the default keybinding for the grammar selector in my keymap but it doesn't work.

![screen shot 2015-10-02 at 10 32 13](https://cloud.githubusercontent.com/assets/6213695/10243190/3cc53d7e-68f7-11e5-9bbd-24502dc11cb7.png)

**Comment by izuzak** [comment]
@thibmaek Have you checked [this section of the debugging guide](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings)? Post the screenshot of the keybinding resolver here and perhaps we can provide advice.

**Comment by thibmaek** [comment]
Just checked with keybinding resolver and split lines is already using it. Tried to overwrite that with something I won't use in any way but still not showing up:

<img width="573" alt="screen shot 2015-10-12 at 19 54 05" src="https://cloud.githubusercontent.com/assets/6213695/10434648/21bf0dbc-711b-11e5-9a48-a83af0044de1.png">

<img width="492" alt="screen shot 2015-10-12 at 19 54 13" src="https://cloud.githubusercontent.com/assets/6213695/10434647/219a5738-711b-11e5-864a-80a4a98ac8a4.png">

**Comment by izuzak** [comment]
@thibmaek You can't change a keybinding like that. 

Give this a try:

```
'.platform-darwin atom-text-editor:not([mini])':
  'shift-cmd-l': 'grammar-selector:show'
```

You can also find more information about keymaps in these guides:
* https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings
* https://atom.io/docs/latest/behind-atom-keymaps-in-depth

**Comment by thibmaek** [comment]
Alright works now, awesome.
